version: "3"

services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql

  back:
    container_name: back
    build: ./back
    environment:
      MYSQL_PASSWORD: password
      MYSQL_USERNAME: root
      MYSQL_HOST: db
      FRONT_ORIGIN: http://localhost:8080
      EDITOR: vim
    ports:
      - 3000:3000
    volumes:
      - ./back:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: /bin/bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"

  front:
    container_name: front
    build: ./front
    environment:
      BASE_URL: http://localhost:3000
      APP_NAME: PFC計算機
    ports:
      - 8080:3000
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    command: yarn dev


  solargraph:
    container_name: solargraph
    build: ./back
    ports:
      - 8091:7658
    volumes:
      - ./back:/app
      - bundle:/usr/local/bundle
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658

volumes:
  mysql:
  bundle:
  node_modules:
